model:
  swinir:
    target: model.SwinIR.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  resnet:
    target: model.ResNet50.ResNet50

dataset:
  target: dataset.HybridDataset.HybridDataset
  params:
    data_dir : "./data/test"  # Create a test dataset directory with the expected structure
    out_size : 224
    crop_type : "center"
    blur_kernel_size : 41
    kernel_list : ['iso', 'aniso']
    kernel_prob : [0.5, 0.5]
    blur_sigma : [0.8, 3.2]
    downsample_range : [2, 4]
    noise_range : [0, 15]
    jpeg_range : [30, 100]
    valid_extensions : [".png", ".jpg", ".jpeg"]


test:
  batch_size: 4
  num_workers: 0
  swin_check_dir: './weights/SwinIR/0010000.pt'
  res_check_dir: ./weights/ResNet/epoch_30.pt
  test_result_dir: ./results

