train:
  # experiment directory path
  exp_dir: "./expriments"
  learning_rate: 1e-3
  momentum: 0.9
  batch_size: 16
  num_workers: 0
  num_epochs: 30 
  log_every: 50
  ckpt_every: 10
  val_every: 100
  resume: ~

dataset:
  train:
    target: dataset.OODDataset.OOD_Dataset
    params:
      data_dir : "./data/train"  # Create a test dataset directory with the expected structure
      out_size : 224
      crop_type : "center"
      blur_kernel_size : 41
      kernel_list : ['iso', 'aniso']
      kernel_prob : [0.5, 0.5]
      blur_sigma : [0.8, 3.2]
      downsample_range : [2, 4]
      noise_range : [0, 15]
      jpeg_range : [30, 100]
      valid_extensions : [".png", ".jpg", ".jpeg"]

  val:
    target: dataset.OODDataset.OOD_Dataset
    params:
      data_dir : "./data/val"  # Create a test dataset directory with the expected structure
      out_size : 224
      crop_type : "center"
      blur_kernel_size : 41
      kernel_list : ['iso', 'aniso']
      kernel_prob : [0.5, 0.5]
      blur_sigma : [0.8, 3.2]
      downsample_range : [2, 4]
      noise_range : [0, 15]
      jpeg_range : [30, 100]
      valid_extensions : [".png", ".jpg", ".jpeg"]
